import manifest from "./bannerManifest.json";

/**
 * Responsive-image data for the local banners in src/public/banner.
 *
 * The manifest is generated by scripts/optimize-images.mjs, so widths and
 * heights come from the encoder that actually wrote the files rather than
 * being typed by hand and drifting the next time an image is replaced.
 *
 * Only local assets are covered. Backend media (api.realestate.aajneeti.social)
 * is served at its original upload size with no derivatives, so there is
 * nothing to build a srcset from — returning null here is the honest answer,
 * and the caller simply omits the attribute. That is a backend change, not one
 * we can fake from the client.
 */
type Entry = { width: number; height: number; srcset: { name: string; w: number }[] };

const BANNERS: Record<string, Entry> = manifest;

export type BannerImage = {
  /** `/banner/x-320.webp 320w, ...` */
  srcset: string;
  width: number;
  height: number;
};

/** Returns null for anything that is not a local /banner/ asset. */
export function bannerImage(src: string | undefined | null): BannerImage | null {
  if (!src) return null;
  const key = src.startsWith("/banner/") ? src.slice("/banner/".length) : null;
  const entry = key ? BANNERS[key] : undefined;
  if (!entry) return null;
  return {
    srcset: entry.srcset.map((v) => `/banner/${v.name} ${v.w}w`).join(", "),
    width: entry.width,
    height: entry.height,
  };
}
