/**
 * Self-hosts the three Google fonts as Latin-only WOFF2.
 *
 * The page was loading a render-blocking stylesheet from fonts.googleapis.com
 * (230ms before a single byte of font arrived), which then pointed at
 * fonts.gstatic.com -- a second origin, a second DNS + TLS handshake, all on
 * the critical path for first paint.
 *
 * Google's CSS declares 35 @font-face blocks covering Cyrillic, Greek,
 * Vietnamese and Latin-Extended. The site is English, so only the 4 blocks
 * whose unicode-range is the basic Latin one are kept. The files themselves are
 * already subset per range by Google, so no local subsetting tool is needed.
 *
 * The axis ranges deliberately match the previous request exactly
 * (Fraunces opsz 9..144, wght 400..600, upright + italic). Widening them would
 * change how text renders, which is out of scope.
 *
 * Usage: node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const URL_ =
  "https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400..600;1,9..144,400..600&family=Manrope:wght@400..700&family=IBM+Plex+Mono:wght@500&display=swap";

// Manrope is requested as a variable font (400..700) rather than four static
// weights: one 24.8 KB file instead of four 24.3 KB ones, rendering identically
// at each of the weights the site actually uses.
// A modern desktop UA makes Google serve WOFF2 rather than legacy formats.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const OUT_DIR = "src/public/fonts";
const CSS_OUT = "src/fonts.css";

/** The basic-Latin subset Google emits; every other range is dropped. */
const LATIN = "U+0000-00FF";

const slug = (family, style, weight) =>
  `${family.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${weight.replace(/\s+/g, "-")}-${style}.woff2`;

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const css = await (await fetch(URL_, { headers: { "User-Agent": UA } })).text();

  const blocks = [...css.matchAll(/@font-face\s*\{[^}]*\}/g)].map((m) => m[0]);
  const kept = blocks.filter((b) => b.includes(`unicode-range: ${LATIN}`));

  console.log(`@font-face blocks: ${blocks.length} -> ${kept.length} (Latin only)`);

  const out = [
    "/* Generated by scripts/fetch-fonts.mjs -- do not edit by hand. */",
    "/* Self-hosted so first paint does not wait on fonts.googleapis.com. */",
    "",
  ];
  let total = 0;

  for (const block of kept) {
    const family = /font-family:\s*'([^']+)'/.exec(block)[1];
    const style = /font-style:\s*(\S+?);/.exec(block)[1];
    const weight = /font-weight:\s*([^;]+);/.exec(block)[1].trim();
    const url = /url\((https:[^)]+)\)/.exec(block)[1];

    const file = slug(family, style, weight);
    const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
    await writeFile(path.join(OUT_DIR, file), buf);
    total += buf.length;
    console.log(`  ${family} ${style} ${weight}  ${(buf.length / 1024).toFixed(1)} KB  -> ${file}`);

    out.push(
      "@font-face {",
      `  font-family: '${family}';`,
      `  font-style: ${style};`,
      `  font-weight: ${weight};`,
      "  font-display: swap;",
      `  src: url('/fonts/${file}') format('woff2');`,
      `  unicode-range: ${/unicode-range:\s*([^;]+);/.exec(block)[1].trim()};`,
      "}",
      "",
    );
  }

  await writeFile(CSS_OUT, out.join("\n"));
  console.log(`\ntotal woff2: ${(total / 1024).toFixed(1)} KB -> ${CSS_OUT}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
